theme: jekyll-theme-minimal

title: [Deepesh Singh]
description: [PhD Student @ University of Queensland]

![alt text](https://github.com/singhdeepesh/singhdeepesh.github.io/blob/master/IMG_0212copy.jpg)
