theme: jekyll-theme-minimal

title: [Deepesh Singh]
description: [PhD Candidate @ University of Queensland]

avatar: https://raw.githubusercontent.com/singhdeepesh/singhdeepesh.github.io/blob/master/IMG_0212copy.jpg

![image](IMG_0212copy.jpg)



